name: SecretLab
version: 0.0.1
main: org.domi.SecretLab
author: Dominicus0830
website: "https://github.com/Dominicus0830?tab=repositories"
api-version: 1.20
description: 팔닥팔닥
depend: [CatFish]
commands:
  게임시작:
    aliases: [ "startGame", "gameStart"]
    description: 게임을 시작합니다.
    permission: domi.start
    permission-message: 테스트 권한이 없습니다.
    usage: /게임시작